package:
  name: annovar
  version: "150617"

source:
  url: http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.revision150617.tar.gz

# test:
#   commands:
    # - which annotate_variation.pl 2>&1 > /dev/null
    # - annotate_variation.pl -h 2>&1 > /dev/null
